#BeakShield DAWSON Portable Config
#Mon Jun 29 08:19:56 CDT 2026
IS_FIRST_LAUNCH=false
SERVER_ADDRESS=localhost
SERVER_AUTH_TOKEN=c092e8c8aae9cb0a1dbeab86d0d3c8fdfcec09f780f52ac06db5286935cf4272
SERVER_FINGERPRINT=E7\:BF\:C4\:B4\:2E\:12\:98\:B7\:9F\:26\:3C\:BE\:C8\:03\:D5\:D2\:EE\:1F\:48\:2B\:57\:CD\:B3\:FD\:E7\:99\:7F\:0C\:6D\:73\:44\:B3
SERVER_PORT=8443
