//
//  StyleProperties.swift
//  
//
//  Created by Ethan Brown on 3/31/26.
//

import Foundation

class StyleProperties {
    static let shared = StyleProperties()
    
    enum Color {
        case blue
        case yellow
        case orange
        case red
        case gray
        case metal
        case brown
        
        var hex: String {
            switch self {
            case .blue:
                return "#2C3E5A"
            case .yellow:
                return "#FFCC33"
            case .orange:
                return "#FF9F1C"
            case .red:
                return "#E31E2C"
            case .gray:
                return "#A8B5C8"
            case .metal:
                return "#4A5A6F"
            case .brown:
                return "#8B5A2B"
            }
        }
    }
    
    let mainHeader = """
        ██████╗       █████╗      ██╗    ██╗      ██████╗      ██████╗      ███╗   ██╗
        ██╔══██╗     ██╔══██╗     ██║    ██║     ██╔════╝     ██╔═══██╗     ████╗  ██║
        ██║  ██║     ███████║     ██║ █╗ ██║     ╚█████╗      ██║   ██║     ██╔██╗ ██║
        ██║  ██║     ██╔══██║     ██║███╗██║      ╚═══██╗     ██║   ██║     ██║╚██╗██║
        ██████╔╝     ██║  ██║     ╚███╔███╔╝     ██████╔╝     ╚██████╔╝     ██║ ╚████║
        ╚═════╝      ╚═╝  ╚═╝      ╚══╝╚══╝      ╚═════╝       ╚═════╝      ╚═╝  ╚═══╝
    """
    
    let dawsonImage = #"""
        ...........................................................................
        .....................................      ................................
        .................................... .1j/>  ...............................
        ..................... ............  <Ymhqoz. ..............................
        .................... '  ......... :j*bzYUdhYi ........    .................
        ................... /m].  .....  'Y8*adbbbkoL' .....   -C> ................
        .................. !Wdmc+`     `!x&oaqrndhoMo)'     `+vmaq' ...............
        .................. >8awOQY\+l}vLO0XY0O~-ZCczLOLn]!-tY0Owo*" ...............
        .................. `Q&abwZOOZpZCcnfuQC>>LLrfnzLmpOOOZwda&z.................
        .................. ld&#*abqmOLQQLJJQOQ)}OOCUUCLCQOmpkoo#Wm: ...............
        ...................'xo*aZpq00OOQJzvcJUffXcxuYL0OOOZdmm*#a(.................
        ................... <O8OhZ[+__}tzOmCux/frzOd0r{-+<~tawdWx" ................
        .................... jkQO;:{Jz)l^I}cwC\nmQ/~^``,l+{+)pQh; .................
        ................... ^kQm(lOZp#8#J[,`-LJ0f;^I]fUp#bbv"0Chx .................
        ................... ]#JZ?<k)jMxw$$dJ(l[>?c0oOU$$$tfJ^JUwd' ................
        ................... caQUx"nU_(0ddQmQ\f{ftxbcLpb0t10_>0XZM! ................
        ................... \&pCJn+{rjffrcjuY)_1zU1Ynjftft-1UYOah^ ................
        ................... CbaawLJut+i>i!:~0u)rZ[:li>>+/xYLObad*>   ..............
        ..................  qdZdhadzkr:;III;~Y0C-;III;;fhzpkohqOdx~;.  ............
        .................  +b*awZqkYhoX{>;:::;<I:;:;!}zhkU#hUfjJCOqmY1,  ..........
        ................  ?qkqboadqUoooULmXj1[?[{|uCdwYpoOw[_xppbZqho*m(` .........
        ................'n#kbbbbko#oW*0tY*ddqmZQQ0OZdwj0&d][xbZQL00qqhk*J! ........
        ............... !**akhkbkkoMZkkddQ0LLQYtxxcJLqbk&/?(bYzQmZZqbhwo#m< .......
        ..............  ?W#qOwL00Qh%OczCCLQQ0OJ/czUCCLOph]}YdzzXLwqzYOpdk#OI ......
        ............. ;z#oab#ppophM%*bmOLUzXULJnYzzJ0wdoq}10pOQQ0dt!!nCqkaoz.......
        ...........  }daMwZObbwdkh8&*wkwdbhbmQXuLOqpdkkMw|fQ0JLOwb/urLCLhh#d~ .....
        .......... 'radhomZZpOZqd&BMWqddqpJQmbkd*hbbhkdohruUdOZZOkQCXJL0bo*kx .....
        ......... `Xaqpokkq*bdhdo8*Zd*dahk/Zqqbbd#kbha*W&zYzkZ00wp*ddpm0k*MdJ  ....
        ........ 'Yampd#bhoaMLJmObkOzahhhomvwkbqwoW*#&MbWqcJ0dwwpda#*ohakhMwL. ....
        ........ jaZmab8M*aooLpoZhk#kMoaMW8JLwwpbo*oa#&ak&CQQqkddahdaooahqoZY .....
        ....... >hmZd8kY(cmQpkwa*MWB%oahbpkooohkbhkqmZp*#MWQmZqhahdaaahkkamd{ .....
        ....... xdQZpu])vYUUqaZOoB&M*wkJYuuULJcccLYnvcJdhM@&wmmmkooooahkkpwQ' .....
        ....... "-f\-1cCQOwh8kOa88ohaoMwUvuJzznnxzJccCw###&%%awmZwbhoaabwdZ; ......
        .....  l\|_1YOmmb#W&%M%&88&hbbbo#hw*aOUYQbMbh#okbkaM88&#hbpqqqqddu" .......
        ...  ,(f{/UwqOc?{q*#&&vm88&%8*ao##M8@@&WB$B&##oaaM8&&&MaQuUQOLz|l  ........
        ...'{Yvz0OUn};   '+|nt ^-u#bpOpka#&mmwpddppb&#ahpwbhq{i^    .    ..........
        ...:/}?+!"'  ,li><>><+]}}Z00n(C\nMb||\\//\|j*bfrC1YLwX-?+~>il;`............
        ...        .',I!i><~++-[[tuCUCQYUn{{11{{{{{}1cYYQYUXx(_+~<i!I:'............
        .............           .   ''.`'.''''''''''. '' '.            ............
        ..........................                         ........................
        ...........................................................................
        ...........................................................................
    """#
}
